= conflang
:toc:                      preamble
:toclevels:                3
:source-highlighter:       pygments
:pygments-style:           algol_nu
:pygments-linenums-mode:   table

<DRAFT>

Configuration language, featuring strong typing and a small but robust feature set.

Written in Bash, compiles to Bash.


== What works
Almost nothing.
Been doing a lot of work to clean up symbol tables, the type system, and `import` statements.
That broke everything.
Oops.

* [ ] Parsing file(s)
* [ ] Importing files
* [ ] Typechecking
* [ ] Evaluates to native bash
* [ ] VM & post-compilation validation

Around a503e1b917aa or so I broke a good amount of core functionality while fixing symbol tables.
Gonna be worse before it gets better.

== Why it do
Learning.

Around 2020 I began learning to write a "real" programming language.
Turns out it's hard.
I found myself consistently hitting conceptual sticking points.
Approaching these in the context of something I already understand very well (bash) is easier.

Many of my recent projects (`mkconf`, `conf`, `shql`) were building towards this goal.

I do not intend for anyone to actually use `conflang`, just as I didn't `shql`.
Journey over destination and all that.


== How it look
.Variable declarations
----
# Untyped key/value pairs.
name : "Marcus";
age  : 30;


# Primitive types.
name @str: "Marcus";
age  @int: 30;


# Complex types.
full_name @list[str]: [
   "Marcus",
   "Aurelius",
];
----

.Typedefs
----
typedef tupl[str, str, int] as Person;

me @Person: {"Marcus", "Aurelius", 30};
----

.Types
----
# @str     Surrounded with double-quotes:  "this is a string"
# @path    Surrounded with single-quotes:  './relative', '~/relative', '/absolute'
# @int     Negative & positive integers:   -1, 0, 1, ...
# @bool    Boolean values:                 true, false
# @list    Lists, any length, same type:   [1, 2, 3], ["one", "two", "three"]
# @tupl    Tuples, set length, any type:   {"Marcus", "Aurelius", 30}
----

.Environment variables
----
homedir   (path): $HOME;
configdir (path): $XDG_CONFIG_HOME;
----

.Variables
----
red    @str: "#AF5F5F";
yellow @str: "#DFAD83";
green  @str: "#5F8787";

good  : green;
uh_oh : yellow;
bad   : red;
----

.Sections
----
key: "val";
key2: key;

Section {
   key: "val";

   key2: key;
   #     ^-- relative reference,
   #         shadows global `key2`

   key3: Section.key;
   #     ^-- absolute reference
}
----

.Others
----
# String interpolation (f-strings).
project_dir @path: f'{$HOME}/projects/';
sub_dir     @path: f'{project_dir}/sub/';

# Type casting.
shell_level: $SHLVL -> int;
----

.Example '`real`' file
----
common {
   colors @list[str] [
      "#C5C5C8",
      "#202121",
   ];
}

window {
   geometry {
      height @int: 100;
      width  @int: 80;
   }

   theme {
      foreground : common.colors[0];
      background : common.colors[1];
   }
}
----
