= conflang
:toc:                      preamble
:toclevels:                3
:source-highlighter:       pygments
:pygments-style:           algol_nu
:pygments-linenums-mode:   table

Strongly typed configuration language, featuring a small but robust feature set.

Written in Bash, compiles to Bash.


== What works
* [x] Parsing
* [x] Typechecking
* [x] Evaluation
* [ ] Importing files
* [ ] VM, FFI, post-compilation validation


== What it is
Aiming to solve common problems with shell configuration files.

`conflang` is strongly typed.
Worry less if users pass in invalid data.
Defining clear types removes both a category of errors, and a fair amount of error handling code.

`conflang` is written in bash.
Dependencies are only `realpath` and `bash` 4+.
No need to install Python3, or other heavy depdencies, just to parse a config file.

`conflang` compiles to bash.
Run it, source the output, everything you need is included.

`conflang` is fast.
(The times below are recorded on my very modest laptop.)
Compiling a reasonably sized file takes ~0.100ms.
Though there's no need to re-compile every time.
The query function can access an element nested 10 level deep 12,000 times per second.


== How it look
.Variable declarations
----
# Untyped key/value pairs.
name : "Marcus";
age  : 30;


# Primitive types.
name @str: "Marcus";
age  @int: 30;


# Complex types.
full_name @list[str]: [
   "Marcus",
   "Aurelius",
];
----

.Types
----
@str     Surrounded with double-quotes:  "this is a string"
@path    Surrounded with single-quotes:  './relative', '~/absolute', '/absolute'
@int     Negative & positive integers:   -1, 0, 1, ...
@bool    Boolean values:                 true, false
@list    Any length, of same type:       [1, 2, 3], ["one", "two", "three"]
@rec     Set length, of any type:        {"Marcus", "Aurelius", 30}
----

.Typedefs
----
typedef rec[str, str, int] as Person;

me @Person: {"Marcus", "Aurelius", 30};
----

.Variables
----
red    @str: "#AF5F5F";
yellow @str: "#DFAD83";
green  @str: "#5F8787";

good  : green;
uh_oh : yellow;
bad   : red;
----

.Sections
----
key  : "val";
key2 : key;

Section {
   key2: key;
   #     ^-- relative reference,
   #         shadows global `key2`

   key3: Section.key;
   #     ^-- absolute reference
}
----

.Others
----
# Environment variables.
homedir   : $HOME;
configdir : $XDG_CONFIG_HOME;

# String interpolation.
project_dir @path: f'{$HOME}/projects/';
sub_dir     @path: f'{project_dir}/sub/';

# Type casting.
shell_level: $SHLVL -> int;
----

.Example '`real`' file
----
common {
   colors @list[str] [
      "#C5C5C8",
      "#202121",
   ];
}

window {
   geometry {
      height @int: 100;
      width  @int: 80;
   }

   theme {
      foreground : common.colors[0];
      background : common.colors[1];
   }
}
----


== What I hope to add
=== Validation
Declare requirements after any expression.
These may be in the form of tests, or directives.

----
config @path: '~/.config/hre-utils/conflang' {
   is_directory.
}
----

`is_directory` here is a directive.
It tests if the directory exist.
If not, runs `mkdir -p` and returns the exit status.

----
config @path: '~/.config/hre-utils/conflang/config' {
   is_file?
   exists?
}
----

`is_file` and `exists` are tests.
If their conditions fail, an error is raised.

Some useful things I can imagine:

. File/directory operations
  .. `exists`
  .. `is_file`, `is_dir`, `is_link`
  .. `can_read`, `can_write`, `can_execute`
. String operations
  .. `non_empty`
  .. `option  [ <opt1>..<optN> ]`
      ... Throws error if text is not present in list of opts
. List operations
  .. `non_empty`
  .. `each  <function>  <args>`
      ... Applies a function to each element of the list

=== Virtual machine
Thinking of writing a simple VM to run the validation steps.
Compile things to a simple set of common instructions.

=== FFI
Write functions in bash that can be used as validation tests/directives.
Hopefully will have a core standard library with things like `is_dir`, `is_file`, `exists`.
Anything additional should be extensible without undue burden.


== Why write this
Learning.

Around 2020 I began learning to write a "real" programming language.
Turns out it's hard.
I found myself consistently hitting conceptual sticking points.
Approaching these in the context of something I already understand very well (bash) is easier.

Many of my recent projects (`mkconf`, `conf`, `shql`) were building towards this goal.

I do not intend for anyone to actually use `conflang`, just as I didn't `shql`.
Journey over destination and all that.
